// <auto-generated />
using System;
using LCM.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LCM.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260319215628_KasaKampanyaAlanlari")]
    partial class KasaKampanyaAlanlari
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LCM.Domain.Entities.Campaign", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AltBaslik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Barkod")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("BaslangicTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Baslik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BitisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("BuyQuantityText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CampaignDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateRange")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DetailText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("DiscountedPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EkleyenKullaniciId")
                        .HasColumnType("int");

                    b.Property<string>("Headline")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsLocalProduction")
                        .HasColumnType("bit");

                    b.Property<string>("KampanyaNotu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MinBasketText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("OriginCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("OriginalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PayQuantityText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PriceUpdateDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SablonId")
                        .HasColumnType("int");

                    b.Property<long>("Sku")
                        .HasColumnType("bigint");

                    b.Property<string>("Subheadline")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitPrice")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Barkod")
                        .IsUnique();

                    b.HasIndex("EkleyenKullaniciId");

                    b.HasIndex("SablonId");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.ToTable("Campaigns");
                });

            modelBuilder.Entity("LCM.Domain.Entities.DigitalLabelSpec", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActiveDisplayArea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DPI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DayanabildigiSicaklik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DesteklenenRenkler")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dimensions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EtiketAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EtiketTipId")
                        .HasColumnType("int");

                    b.Property<string>("Inch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LedDesteklenenRenkler")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Olculer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PageSwitch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TahminiPilOmru")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ViewingAngle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EtiketTipId");

                    b.ToTable("DigitalLabelSpecs");
                });

            modelBuilder.Entity("LCM.Domain.Entities.LabelType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EtiketTipi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LabelTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EtiketTipi = "E50"
                        },
                        new
                        {
                            Id = 2,
                            EtiketTipi = "E60"
                        },
                        new
                        {
                            Id = 3,
                            EtiketTipi = "E75"
                        });
                });

            modelBuilder.Entity("LCM.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("RolAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RolAdi = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            RolAdi = "KampanyaYonetici"
                        },
                        new
                        {
                            Id = 3,
                            RolAdi = "VeriGirisi"
                        },
                        new
                        {
                            Id = 4,
                            RolAdi = "Operator"
                        },
                        new
                        {
                            Id = 5,
                            RolAdi = "Goruntuleyici"
                        });
                });

            modelBuilder.Entity("LCM.Domain.Entities.SystemSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<string>("AyarAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SystemSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AktifMi = false,
                            AyarAdi = "KampanyaEkleCaptcha"
                        },
                        new
                        {
                            Id = 2,
                            AktifMi = false,
                            AyarAdi = "SablonEkleCaptcha"
                        },
                        new
                        {
                            Id = 3,
                            AktifMi = false,
                            AyarAdi = "KullaniciEkleCaptcha"
                        });
                });

            modelBuilder.Entity("LCM.Domain.Entities.Template", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EkleyenKullaniciId")
                        .HasColumnType("int");

                    b.Property<int>("EtiketTipId")
                        .HasColumnType("int");

                    b.Property<string>("LayoutKodu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("SablonAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SablonFotoYolu")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EkleyenKullaniciId");

                    b.HasIndex("EtiketTipId");

                    b.ToTable("Templates");
                });

            modelBuilder.Entity("LCM.Domain.Entities.TemplateField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<string>("AlanAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SablonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SablonId");

                    b.ToTable("TemplateFields");
                });

            modelBuilder.Entity("LCM.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<string>("SifreHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("KullaniciAdi")
                        .IsUnique();

                    b.HasIndex("RolId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LCM.Domain.Entities.Campaign", b =>
                {
                    b.HasOne("LCM.Domain.Entities.User", "EkleyenKullanici")
                        .WithMany()
                        .HasForeignKey("EkleyenKullaniciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LCM.Domain.Entities.Template", "Sablon")
                        .WithMany("Kampanyalar")
                        .HasForeignKey("SablonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EkleyenKullanici");

                    b.Navigation("Sablon");
                });

            modelBuilder.Entity("LCM.Domain.Entities.DigitalLabelSpec", b =>
                {
                    b.HasOne("LCM.Domain.Entities.LabelType", "EtiketTip")
                        .WithMany()
                        .HasForeignKey("EtiketTipId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EtiketTip");
                });

            modelBuilder.Entity("LCM.Domain.Entities.Template", b =>
                {
                    b.HasOne("LCM.Domain.Entities.User", "EkleyenKullanici")
                        .WithMany()
                        .HasForeignKey("EkleyenKullaniciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LCM.Domain.Entities.LabelType", "EtiketTip")
                        .WithMany("Templates")
                        .HasForeignKey("EtiketTipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EkleyenKullanici");

                    b.Navigation("EtiketTip");
                });

            modelBuilder.Entity("LCM.Domain.Entities.TemplateField", b =>
                {
                    b.HasOne("LCM.Domain.Entities.Template", "Sablon")
                        .WithMany("Alanlar")
                        .HasForeignKey("SablonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sablon");
                });

            modelBuilder.Entity("LCM.Domain.Entities.User", b =>
                {
                    b.HasOne("LCM.Domain.Entities.Role", "Rol")
                        .WithMany("Users")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("LCM.Domain.Entities.LabelType", b =>
                {
                    b.Navigation("Templates");
                });

            modelBuilder.Entity("LCM.Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("LCM.Domain.Entities.Template", b =>
                {
                    b.Navigation("Alanlar");

                    b.Navigation("Kampanyalar");
                });
#pragma warning restore 612, 618
        }
    }
}
