// <auto-generated />
using System;
using LCM.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LCM.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LCM.Domain.Entities.Campaign", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AltBaslik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Barkod")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("BaslangicTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Baslik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BitisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("BuyQuantityText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CampaignDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CurrentOwnerKullaniciId")
                        .HasColumnType("int");

                    b.Property<string>("DateRange")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DetailText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("DiscountedPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EkleyenKullaniciId")
                        .HasColumnType("int");

                    b.Property<string>("Headline")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsLocalProduction")
                        .HasColumnType("bit");

                    b.Property<string>("KampanyaNotu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MinBasketText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("OnayYorumu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("OriginalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PayQuantityText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PriceUpdateDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SablonId")
                        .HasColumnType("int");

                    b.Property<long>("Sku")
                        .HasColumnType("bigint");

                    b.Property<string>("Subheadline")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitPrice")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Barkod")
                        .IsUnique();

                    b.HasIndex("CurrentOwnerKullaniciId");

                    b.HasIndex("EkleyenKullaniciId");

                    b.HasIndex("SablonId");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.ToTable("Campaigns");
                });

            modelBuilder.Entity("LCM.Domain.Entities.CampaignLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aksiyon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CampaignId")
                        .HasColumnType("int");

                    b.Property<string>("HedefEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("Yorum")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.HasIndex("KullaniciId");

                    b.ToTable("CampaignLogs");
                });

            modelBuilder.Entity("LCM.Domain.Entities.CampaignStore", b =>
                {
                    b.Property<int>("CampaignId")
                        .HasColumnType("int");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.HasKey("CampaignId", "StoreId");

                    b.HasIndex("StoreId");

                    b.ToTable("CampaignStores");
                });

            modelBuilder.Entity("LCM.Domain.Entities.DigitalLabelSpec", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActiveDisplayArea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DPI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DayanabildigiSicaklik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DesteklenenRenkler")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dimensions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EtiketAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EtiketTipId")
                        .HasColumnType("int");

                    b.Property<string>("Inch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LedDesteklenenRenkler")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Olculer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PageSwitch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TahminiPilOmru")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ViewingAngle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EtiketTipId");

                    b.ToTable("DigitalLabelSpecs");
                });

            modelBuilder.Entity("LCM.Domain.Entities.EslApiSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Algorithm")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApiUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerStoreCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeaderPrefix")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecretKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EslApiSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessKey = "",
                            Algorithm = "HS256",
                            ApiUrl = "http://192.168.1.1:8080/prismart/integration",
                            CustomerStoreCode = "",
                            HeaderPrefix = "HSIAM1",
                            SecretKey = ""
                        });
                });

            modelBuilder.Entity("LCM.Domain.Entities.EslEslestirme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("BasariliMi")
                        .HasColumnType("bit");

                    b.Property<string>("EslBarkod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EslestirmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("GonderilenJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HataMesaji")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IslemTipi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KampanyaId")
                        .HasColumnType("int");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<bool>("Override")
                        .HasColumnType("bit");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KampanyaId");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("StoreId");

                    b.ToTable("EslEslestirmeler");
                });

            modelBuilder.Entity("LCM.Domain.Entities.EslField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<string>("VariableName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EslFields");
                });

            modelBuilder.Entity("LCM.Domain.Entities.EslGonderimLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Basarili")
                        .HasColumnType("bit");

                    b.Property<int>("BasariliKampanya")
                        .HasColumnType("int");

                    b.Property<int>("BasarisizKampanya")
                        .HasColumnType("int");

                    b.Property<int?>("EslJobId")
                        .HasColumnType("int");

                    b.Property<string>("GonderilenJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("GonderimZamani")
                        .HasColumnType("datetime2");

                    b.Property<string>("HataMesaji")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HttpStatusKod")
                        .HasColumnType("int");

                    b.Property<int?>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<string>("StoreCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tetikleyen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ToplamKampanya")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EslJobId");

                    b.HasIndex("KullaniciId");

                    b.ToTable("EslGonderimLogs");
                });

            modelBuilder.Entity("LCM.Domain.Entities.EslJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AktifGonder")
                        .HasColumnType("bit");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<TimeOnly>("CalismaZamani")
                        .HasColumnType("time");

                    b.Property<string>("JobAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OlusturanKullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<bool>("PlanlanmisGonder")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SonCalisma")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OlusturanKullaniciId");

                    b.ToTable("EslJobs");
                });

            modelBuilder.Entity("LCM.Domain.Entities.EslTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CronExpression")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LedColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LedCount")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LedOffTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LedOnTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LedSleepTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("SqlScript")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("StoreId");

                    b.ToTable("EslTasks");
                });

            modelBuilder.Entity("LCM.Domain.Entities.EslTaskLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("BasariliMi")
                        .HasColumnType("bit");

                    b.Property<int?>("EslSayisi")
                        .HasColumnType("int");

                    b.Property<int>("EslTaskId")
                        .HasColumnType("int");

                    b.Property<string>("GonderilenJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HataMesaji")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LogTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mesaj")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EslTaskId");

                    b.ToTable("EslTaskLogs");
                });

            modelBuilder.Entity("LCM.Domain.Entities.FieldMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BizimAlanAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("EslFieldId")
                        .HasColumnType("int");

                    b.Property<int>("SablonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EslFieldId");

                    b.HasIndex("SablonId", "BizimAlanAdi")
                        .IsUnique();

                    b.ToTable("FieldMappings");
                });

            modelBuilder.Entity("LCM.Domain.Entities.Font", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DosyaAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EklenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("FontAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FontWeight")
                        .HasColumnType("int");

                    b.Property<bool>("Italic")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Fonts");
                });

            modelBuilder.Entity("LCM.Domain.Entities.LabelType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EtiketTipi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LabelTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EtiketTipi = "E50"
                        },
                        new
                        {
                            Id = 2,
                            EtiketTipi = "E60"
                        },
                        new
                        {
                            Id = 3,
                            EtiketTipi = "E75"
                        });
                });

            modelBuilder.Entity("LCM.Domain.Entities.Layout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LayoutJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LayoutKodu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Layouts");
                });

            modelBuilder.Entity("LCM.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("RolAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RolAdi = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            RolAdi = "KampanyaYonetici"
                        },
                        new
                        {
                            Id = 3,
                            RolAdi = "VeriGirisi"
                        },
                        new
                        {
                            Id = 4,
                            RolAdi = "Operator"
                        },
                        new
                        {
                            Id = 5,
                            RolAdi = "Goruntuleyici"
                        });
                });

            modelBuilder.Entity("LCM.Domain.Entities.SmtpSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GonderenAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GonderenEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Port")
                        .HasColumnType("int");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SslAktif")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("SmtpSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GonderenAdi = "LCM Sistem",
                            GonderenEmail = "",
                            Host = "",
                            KullaniciAdi = "",
                            Port = 587,
                            Sifre = "",
                            SslAktif = true
                        });
                });

            modelBuilder.Entity("LCM.Domain.Entities.Store", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<string>("StoreCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StoreName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Stores");
                });

            modelBuilder.Entity("LCM.Domain.Entities.SystemSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<string>("AyarAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SystemSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AktifMi = false,
                            AyarAdi = "KampanyaEkleCaptcha"
                        },
                        new
                        {
                            Id = 2,
                            AktifMi = false,
                            AyarAdi = "SablonEkleCaptcha"
                        },
                        new
                        {
                            Id = 3,
                            AktifMi = false,
                            AyarAdi = "KullaniciEkleCaptcha"
                        },
                        new
                        {
                            Id = 4,
                            AktifMi = true,
                            AyarAdi = "EslOnayPopupAktif"
                        },
                        new
                        {
                            Id = 5,
                            AktifMi = true,
                            AyarAdi = "EslOverrideAktif"
                        },
                        new
                        {
                            Id = 6,
                            AktifMi = true,
                            AyarAdi = "DashboardOtomatikGuncelleme"
                        },
                        new
                        {
                            Id = 7,
                            AktifMi = false,
                            AyarAdi = "KampanyaOnayaGonderilsinMi"
                        },
                        new
                        {
                            Id = 8,
                            AktifMi = false,
                            AyarAdi = "MailBildirimleriAktif"
                        },
                        new
                        {
                            Id = 9,
                            AktifMi = false,
                            AyarAdi = "OnayMailiGonderilsinMi"
                        });
                });

            modelBuilder.Entity("LCM.Domain.Entities.Template", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EkleyenKullaniciId")
                        .HasColumnType("int");

                    b.Property<int>("EtiketTipId")
                        .HasColumnType("int");

                    b.Property<string>("LayoutJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LayoutKodu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("SablonAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SablonFotoYolu")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EkleyenKullaniciId");

                    b.HasIndex("EtiketTipId")
                        .IsUnique();

                    b.ToTable("Templates");
                });

            modelBuilder.Entity("LCM.Domain.Entities.TemplateField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<string>("AlanAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SablonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SablonId");

                    b.ToTable("TemplateFields");
                });

            modelBuilder.Entity("LCM.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<bool>("CokluEslestirmeIzni")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("HizliEslestirmeIzni")
                        .HasColumnType("bit");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<string>("SifreHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("KullaniciAdi")
                        .IsUnique();

                    b.HasIndex("RolId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LCM.Domain.Entities.UserStore", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "StoreId");

                    b.HasIndex("StoreId");

                    b.ToTable("UserStores");
                });

            modelBuilder.Entity("LCM.Domain.Entities.Campaign", b =>
                {
                    b.HasOne("LCM.Domain.Entities.User", "CurrentOwner")
                        .WithMany()
                        .HasForeignKey("CurrentOwnerKullaniciId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LCM.Domain.Entities.User", "EkleyenKullanici")
                        .WithMany()
                        .HasForeignKey("EkleyenKullaniciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LCM.Domain.Entities.Template", "Sablon")
                        .WithMany("Kampanyalar")
                        .HasForeignKey("SablonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CurrentOwner");

                    b.Navigation("EkleyenKullanici");

                    b.Navigation("Sablon");
                });

            modelBuilder.Entity("LCM.Domain.Entities.CampaignLog", b =>
                {
                    b.HasOne("LCM.Domain.Entities.Campaign", "Campaign")
                        .WithMany("Loglar")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LCM.Domain.Entities.User", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Campaign");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("LCM.Domain.Entities.CampaignStore", b =>
                {
                    b.HasOne("LCM.Domain.Entities.Campaign", "Campaign")
                        .WithMany("CampaignStores")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LCM.Domain.Entities.Store", "Store")
                        .WithMany()
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("LCM.Domain.Entities.DigitalLabelSpec", b =>
                {
                    b.HasOne("LCM.Domain.Entities.LabelType", "EtiketTip")
                        .WithMany()
                        .HasForeignKey("EtiketTipId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EtiketTip");
                });

            modelBuilder.Entity("LCM.Domain.Entities.EslEslestirme", b =>
                {
                    b.HasOne("LCM.Domain.Entities.Campaign", "Kampanya")
                        .WithMany()
                        .HasForeignKey("KampanyaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LCM.Domain.Entities.User", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LCM.Domain.Entities.Store", "Store")
                        .WithMany()
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kampanya");

                    b.Navigation("Kullanici");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("LCM.Domain.Entities.EslGonderimLog", b =>
                {
                    b.HasOne("LCM.Domain.Entities.EslJob", "EslJob")
                        .WithMany()
                        .HasForeignKey("EslJobId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LCM.Domain.Entities.User", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("EslJob");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("LCM.Domain.Entities.EslJob", b =>
                {
                    b.HasOne("LCM.Domain.Entities.User", "OlusturanKullanici")
                        .WithMany()
                        .HasForeignKey("OlusturanKullaniciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OlusturanKullanici");
                });

            modelBuilder.Entity("LCM.Domain.Entities.EslTask", b =>
                {
                    b.HasOne("LCM.Domain.Entities.Store", "Store")
                        .WithMany()
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Store");
                });

            modelBuilder.Entity("LCM.Domain.Entities.EslTaskLog", b =>
                {
                    b.HasOne("LCM.Domain.Entities.EslTask", "EslTask")
                        .WithMany("Logs")
                        .HasForeignKey("EslTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EslTask");
                });

            modelBuilder.Entity("LCM.Domain.Entities.FieldMapping", b =>
                {
                    b.HasOne("LCM.Domain.Entities.EslField", "EslField")
                        .WithMany("Mappings")
                        .HasForeignKey("EslFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LCM.Domain.Entities.Template", "Sablon")
                        .WithMany()
                        .HasForeignKey("SablonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EslField");

                    b.Navigation("Sablon");
                });

            modelBuilder.Entity("LCM.Domain.Entities.Template", b =>
                {
                    b.HasOne("LCM.Domain.Entities.User", "EkleyenKullanici")
                        .WithMany()
                        .HasForeignKey("EkleyenKullaniciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LCM.Domain.Entities.LabelType", "EtiketTip")
                        .WithMany("Templates")
                        .HasForeignKey("EtiketTipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EkleyenKullanici");

                    b.Navigation("EtiketTip");
                });

            modelBuilder.Entity("LCM.Domain.Entities.TemplateField", b =>
                {
                    b.HasOne("LCM.Domain.Entities.Template", "Sablon")
                        .WithMany("Alanlar")
                        .HasForeignKey("SablonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sablon");
                });

            modelBuilder.Entity("LCM.Domain.Entities.User", b =>
                {
                    b.HasOne("LCM.Domain.Entities.Role", "Rol")
                        .WithMany("Users")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("LCM.Domain.Entities.UserStore", b =>
                {
                    b.HasOne("LCM.Domain.Entities.Store", "Store")
                        .WithMany()
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LCM.Domain.Entities.User", "User")
                        .WithMany("YetkiliStoreler")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Store");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LCM.Domain.Entities.Campaign", b =>
                {
                    b.Navigation("CampaignStores");

                    b.Navigation("Loglar");
                });

            modelBuilder.Entity("LCM.Domain.Entities.EslField", b =>
                {
                    b.Navigation("Mappings");
                });

            modelBuilder.Entity("LCM.Domain.Entities.EslTask", b =>
                {
                    b.Navigation("Logs");
                });

            modelBuilder.Entity("LCM.Domain.Entities.LabelType", b =>
                {
                    b.Navigation("Templates");
                });

            modelBuilder.Entity("LCM.Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("LCM.Domain.Entities.Template", b =>
                {
                    b.Navigation("Alanlar");

                    b.Navigation("Kampanyalar");
                });

            modelBuilder.Entity("LCM.Domain.Entities.User", b =>
                {
                    b.Navigation("YetkiliStoreler");
                });
#pragma warning restore 612, 618
        }
    }
}
